const ADD_LINK_REQUEST = "ADD_LINK_REQUEST";
const ADD_LINK_SUCCESS = "ADD_LINK_SUCCESS";
const ADD_LINK_FAILURE = "ADD_LINK_FAILURE";

export default {
  ADD_LINK_REQUEST,
  ADD_LINK_SUCCESS,
  ADD_LINK_FAILURE
};
